
hero:
  name: 安琪拉
  word: 火焰是我最喜欢的玩具
  Hp: 445.5

hero2: {name: 安琪拉, word: 火焰是我最喜欢的玩具, Hp: 445}
heros_name:
  - 安琪拉
  - 黄忠
  - 小乔

heros:
  - name: 黄忠
    word: 周日
    Hp: 440


heros_name_list:
  -
    - 安奇拉
    - 小乔
    - 黄忠
    - 曹操

heros_name_word:
  -
    - 安琪拉
    - aaa
  -
    - 小乔
    - bbb
  -
    - 黄忠
    - ccc
  -
    - 曹操
    - ddd

code:
#   name: code
#   request:
    - http://kdtx-test.itheima.net/api/captchaImage

########################登录测试用例############################
login1:  ###post,字典形式{login1:[{"username":"admin","password":"HM_2023_test"}]}
    username: admin
    password: HM_2023_test
    code: 2

login:  ###post  数组嵌套{"key":[[admin,HM_2023_test,2]]}
  #####登录成功  用户名，密码，code 全部参数正确
  - [admin,HM_2023_test ,2]
  ######登录失败(测试名为空)
  - ['', HM_2023_test, 2]
  ######登录失败(未注册用户名)
  - [abc, HM_2023_test , 2 ]
  ######登录失败（验证码错误）
  - [admin, HM_2023_test , 1]

user_login:
  #用户名，密码，code
  - [admin , HM_2023_test , 2]
##########################################################################

#################课程列表查询用例1#######################
####显示满足条件的课程信息（输入存在的课程介绍，课程名称，课程学科，课程价格，适用人群）
search:
   name: 测试开发提升课01
   subject: 6
   price: 899
   applicablePerson: 2
   info: 测试开发提升课01

#####课程列表查询用例2
####查询不存在的信息
####举例，输入不存在的课程名称
search2:
   name: hhhhhh
   subject: 6
   price: 899
   applicablePerson: 2
   info: 测试开发提升课01

#####课程列表查询用例3
####显示默认设置的数据（不输入查询参数）
search3:
   name:
   subject:
   price:
   applicablePerson:
   info:

#####课程列表查询用例4
####查询失败（用户未登录）
search4:
   name:
   subject:
   price:
   applicablePerson:
   info:
##############################################################


#################添加课程用例#######################
###[name,subject,price,applicablePerson,info]
add1:
   ####添加成功（全部参数填写正确）
   - ['软件开发课01',6,999,3,'这是一个软件开发课01']
   ####添加成功（全部必填参数填写正确）
   - [ '软件开发课01',6,999,3,'' ]
add2:
   ####添加失败（课程名称为空）
   - [ ' ',6,999,3 ,' ']
  ####添加失败（课程名称超过30个字符）
   - [ '测试开发提升课011111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111', 8, 999 , 3 ,' ']
  ####添加失败（课程学科为空）
   - [ '软件开发课01',' ',999,3 ,' ']
  ####添加失败（课程学科为空课程学科长度大于1位）
   - [ '软件开发课01',66,999,3 ,'']
  ####添加失败（课程学科非数字）
   - [ '软件开发课01','a',999,3 ,'']
  ####添加失败（课程学科可取范围之外的值）
   - [ '软件开发课01',5,999,3 ,'']
add3:
  ####添加失败（未登录）
   - [ '软件开发课01',6,999,3 ,'']
##############################################################

#################修改课程用例#######################
###[id,name,subject,price,applicablePerson,info]
modify1:
   ####课程修改成功（必填参数课程id正确）
   - ['93','接口测试001', 6, '800','2','课程介绍001']
   ####课程修改成功（全部必填参数填写正确）
   - [ '100','接口测试001',6,800,3,'课程介绍001' ]
modify2:
   ####课程修改失败（课程ID为空）
   - [ '','接口测试001',6,999,3 ,'课程介绍001']
  ####课程修改失败（课程ID非数字）
   - [ 'a','测试开发提升课01',8,999,3 ,'']
  ####课程修改失败（课程ID不存在）
   - [ '55555555','软件开发课01',6,999,3 ,'']
modify3:
  ####课程修改失败（用户未登录）
   - [ '100','接口测试001',6,800,3,'课程介绍001' ]
##############################################################
#################删除课程用例#######################
###[id,name,subject,price,applicablePerson,info]
del0:
  ####课程删除成功（必填参数课程id存在）
  id: 23056458704402081

del1:
   ####课程删除失败（课程ID为空）
  id1: ''
   ####课程删除失败（课程ID非数字）
  id2: 'a'
  ####课程删除失败（课程ID不存在）
  id3: 93

del2:
  - [' ','接口测试001']
  - [93,'接口测试001']

del3:
  ####课程修改失败（用户未登录）
   id: 100
##############################################################


######allure 动态自定义报告
text:
  title: 显示满足条件的课程信息（输入存在的课程介绍，课程名称，课程学科，课程价格，适用人群）
  story: 查询列表story


